version: "3"

name: broccoli-development

services:
  database:
    #profiles:
     # - donotstart
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-broccoli}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB:-broccoli}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/database:/var/lib/postgresql/data